name: flutter_chat_ui_starter
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  simple_animations: ^1.1.3
  page_transition: ^1.1.7+6
  firebase_core: ^1.0.3
  firebase_auth: ^1.0.2
  cloud_firestore: ^1.0.4
  modal_progress_hud: ^0.1.3
  circular_reveal_animation: ^2.0.0
  flutter_slidable: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:


  uses-material-design: true

  assets:
   - assets/images/

  fonts:
    - family: RobotoSlab
      fonts:
        - asset: fonts/RobotoSlab-VariableFont_wght.ttf
